version: '2'
services:
    samaladoum-app:
        image: samaladoum
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://samaladoum-mysql:3306/samaladoum?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    samaladoum-mysql:
        extends:
            file: mysql.yml
            service: samaladoum-mysql
